apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment

spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      initContainers:
        - name: wait-for-ollama
          image: busybox:1.36
          command: ["/bin/sh", "-c"]
          args:
            - >-
              until wget -qO- --spider http://ollama-service:11434/api/tags; do
                echo "Waiting for Ollama at http://ollama-service:11434...";
                sleep 2;
              done;
              echo "Ollama is up.";
      containers:
        - name: backend
          image: infinite-chat-api:latest
          ports:
          - containerPort: 8000
          imagePullPolicy: IfNotPresent  # For local images
          envFrom:
            - configMapRef:
                name: backend-env
          volumeMounts:
            - name: vector-db-storage
              mountPath: /opt/vector_db
      volumes:
        - name: vector-db-storage
          persistentVolumeClaim:
            claimName: vector-db-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ollama-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ollama
  template:
    metadata:
      labels:
        app: ollama
    spec:
      initContainers:
        - name: ollama-init
          image: ollama/ollama:latest
          command: ["/bin/sh", "-c", "/scripts/ollama-init.sh"]
          volumeMounts:
            - name: ollama-data
              mountPath: /root/.ollama
            - name: init-scripts
              mountPath: /scripts
      containers:
        - name: ollama
          image: ollama/ollama:latest
          ports:
          - containerPort: 11434
          imagePullPolicy: IfNotPresent
          volumeMounts:
          - name: ollama-data
            mountPath: /root/.ollama
      volumes:
      - name: ollama-data
        persistentVolumeClaim:
          claimName: ollama-pvc
      - name: init-scripts
        configMap:
          name: backend-env
          defaultMode: 0755
---
apiVersion: v1
kind: Service
metadata:
  name: ollama-service
spec:
  selector:
    app: ollama
  ports:
    - protocol: TCP
      port: 11434
      targetPort: 11434