apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment

spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: infinite-chat-front:latest
          ports:
          - containerPort: 8080
          imagePullPolicy: IfNotPresent  # For local images
          env:
            - name: NODE_ENV
              value: production
            - name: VITE_API_URL
              value: /api

---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080