app = "infinite-chat"
primary_region = "ams"

[http_service]
auto_start_machines = true
auto_stop_machines = true
force_https = true
internal_port = 8000
min_machines_running = 1
processes = [ "app" ]

[mounts]
source = "chat_data"
destination = "/opt/vector_db"

[[vm]]
cpu_kind = "shared"
cpus = 1
memory = "1gb"
memory_mb = 1024